version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ubuntu/api


hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 180
      runas: ubuntu
      